[package]
name = "dng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { git = "https://github.com/chadat23/Image.git" }
jpeg = { git = "https://github.com/chadat23/Jpeg.git" }
