pub(crate) enum Tag {        
    NewSubFileType_254 = 254,  // 0x00FE  A general indication of the kind of data contained in this subfile.	Baseline	Req'd in LC RFP97-6 Section C.4.7., Usage rule in JHOVE TIFF module., Mandatory for TIFF/EP.
    SubfileType_255 = 255,  // 0x00FF  A general indication of the kind of data contained in this subfile.	Baseline	 
    ImageWidth_256 = 256,  // 0x0100  The number of columns in the image, i.e., the number of pixels per row.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7. Provide actual pixel count., Req'd in LC NDNP TIFF profile. See Appendix B. Image width in pixels., Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1, Mandatory for TIFF/EP., Mandatory for primary TIFF IFD in Exif. (Note that for JPEG compressed data, a JPEG marker is used instead of this tag. See JEITA CP-3451: Exif 2.2.)
    ImageLength_257 = 257,  // 0x0101  The number of rows of pixels in the image.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7. Provide actual pixel count., Req'd in LC NDNP TIFF profile. Image length in pixels., Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1, Mandatory for TIFF/EP., Mandatory for primary TIFF IFD in Exif. (Note that for JPEG compressed data, a JPEG marker is used instead of this tag. See JEITA CP-3451: Exif 2.2.)
    BitsPerSample_258 = 258,  // 0x0102  Number of bits per component.	Baseline, Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7., Mandatory for TIFF 6.0 classes G, P, R, and Y.1, Mandatory for TIFF/EP., Mandatory for primary TIFF IFD in Exif. (Note that for JPEG compressed data, a JPEG marker is used instead of this tag. See JEITA CP-3451: Exif 2.2.), Required by DLF benchmark guidelines (available via Internet Archive).
    Compression_259 = 259,  // 0x0103  Compression scheme used on the image data.	Baseline	Listed in LoC Baseline Tags. Sample values: 1=uncompressed and 4=CCITT Group 4., Req'd in LC RFP97-6 Section C.4.7., Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1, Mandatory for TIFF/EP., Mandatory for primary TIFF IFD in Exif. (Note that this tag is omitted when primary image is JPEG compressed. See JEITA CP-3451: Exif 2.2.), Required by DLF benchmark guidelines (available via Internet Archive).
    PhotometricInterpretation_262 = 262,  // 0x0106  The color space of the image data.	Baseline	Listed in LoC Baseline Tags. Sample values: 1=black is zero and 2=RGB. Document also states "RGB is assumed to be sRGB; if RGB, an ICC profile should be present in the 34675 tag.", Req'd in LC RFP97-6 Section C.4.7, Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1, Mandatory for TIFF/EP., Mandatory for GeoTIFF_1_0., Mandatory for primary TIFF IFD in Exif. (Note that for JPEG compressed data, a JPEG marker is used instead of this tag. See JEITA CP-3451: Exif 2.2.), Required by DLF benchmark guidelines (available via Internet Archive).
    Threshholding_263 = 263,  // 0x0107  For black and white TIFF files that represent shades of gray, the technique used to convert from gray to black and white pixels.	Baseline	Usage rule in JHOVE TIFF module.
    CellWidth_264 = 264,  // 0x0108  The width of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.	Baseline	 
    CellLength_265 = 265,  // 0x0109  The length of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.	Baseline	Usage rule in JHOVE TIFF module.
    FillOrder_266 = 266,  // 0x010A  The logical order of bits within a byte.	Baseline	 
    DocumentName_269 = 269,  // 0x010D  The name of the document from which this image was scanned.	Extended	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7. Provide collection identifier and filename., Req'd in LC NDNP TIFF profile. Provide microfilm reel number or normalized LCCN., Also used by HD Photo.
    ImageDescription_270 = 270,  // 0x010E  A string that describes the subject of the image.	Baseline	Also used by HD Photo
    Make_271 = 271,  // 0x010F  The scanner manufacturer.	Baseline	Listed in LoC Baseline Tags., Req'd in LC NDNP TIFF profile., Also used by HD Photo., Mandatory for TIFF/EP.
    Model_272 = 272,  // 0x0110  The scanner model name or number.	Baseline	Listed in LoC Baseline Tags., Req'd in LC NDNP TIFF profile. Provide "model name, model number, serial number.", Also used by HD Photo., Mandatory for TIFF/EP.
    StripOffsets_273 = 273,  // 0x0111  For each strip, the byte offset of that strip.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7, Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1 (Files outside of these classes may use tiles and tags 322, 323, 324, and 325; Comments welcome.), Mandatory in TIFF/EP for stripped images., For Exif, mandatory in primary TIFF IFD.
    Orientation_274 = 274,  // 0x0112  The orientation of the image with respect to the rows and columns.	Baseline	Req'd in LC NDNP TIFF profile., Mandatory for TIFF/EP.
    SamplesPerPixel_277 = 277,  // 0x0115  The number of components per pixel.	Baseline	Listed in LoC Baseline Tags. Sample values: 8 8 8., Req'd in LC RFP97-6 Section C.4.7., Req'd in LC NDNP TIFF profile., Mandatory for TIFF 6.0 classes R and Y.1, For Exif, mandatory in primary TIFF IFD., Required by DLF benchmark guidelines
    RowsPerStrip_278 = 278,  // 0x0116  The number of rows per strip.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7., Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1 (Files outside of these classes may use tiles and tags 322, 323, 324, and 325; Comments welcome.), Mandatory in TIFF/EP for stripped images., For Exif, mandatory in primary TIFF IFD.
    StripByteCounts_279 = 279,  // 0x0117  For each strip, the number of bytes in the strip after compression.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7, Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1 (Files outside of these classes may use tiles and tags 322, 323, 324, and 325; Comments welcome.), Mandatory in TIFF/EP for stripped images., For Exif, mandatory in primary TIFF IFD.
    MinSampleValue_280 = 280,  // 0x0118  The minimum component value used.	Baseline	 
    MaxSampleValue_281 = 281,  // 0x0119  The maximum component value used.	Baseline	 
    XResolution_282 = 282,  // 0x011A  The number of pixels per ResolutionUnit in the ImageWidth direction.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7. Provide actual pixel count or pixels per inch., Req'd in LC NDNP TIFF profile. Xresolution is a Rational; ImageWidth (Tag 256) is the numerator and the length of the source (measured in the units specified in ResolutionUnit (Tag 296)) is the denominator., Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1, Mandatory for TIFF/EP., For Exif, mandatory in primary TIFF IFD., Required by DLF benchmark guidelines (available through Internet Archive).
    YResolution_283 = 283,  // 0x011B  The number of pixels per ResolutionUnit in the ImageLength direction.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7. Provide actual pixel count or pixels per inch., Req'd in LC NDNP TIFF profile. Yresolution is a Rational; ImageLength (Tag 257) is the numerator and the width of the source (measured in the units specified in ResolutionUnit (Tag 296)) is the denominator., Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1, Mandatory for TIFF/EP., For Exif, mandatory in primary TIFF IFD., Required by DLF benchmark guidelines (available through Internet Archive).
    PlanarConfiguration_284 = 284,  // 0x011C  How the components of each pixel are stored.	Baseline	Mandatory for TIFF/EP.
    PageName_285 = 285,  // 0x011D  The name of the page from which this image was scanned.	Extended	Also used by HD Photo
    XPosition_286 = 286,  // 0x011E  X position of the image.	Extended	 
    YPosition_287 = 287,  // 0x011F  Y position of the image.	Extended	 
    FreeOffsets_288 = 288,  // 0x0120  For each string of contiguous unused bytes in a TIFF file, the byte offset of the string.	Baseline	 
    FreeByteCounts_289 = 289,  // 0x0121  For each string of contiguous unused bytes in a TIFF file, the number of bytes in the string.	Baseline	 
    GrayResponseUnit_290 = 290,  // 0x0122  The precision of the information contained in the GrayResponseCurve.	Baseline	 
    GrayResponseCurve_291 = 291,  // 0x0123  For grayscale data, the optical density of each possible pixel value.	Baseline	 
    T4Options_292 = 292,  // 0x0124  Options for Group 3 Fax compression	Extended	 
    T6Options_293 = 293,  // 0x0125  Options for Group 4 Fax compression	Extended	 
    ResolutionUnit_296 = 296,  // 0x0128  The unit of measurement for XResolution and YResolution.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7. Code 1 for actual pixel count or 2 for pixels per inch., Req'd in LC NDNP TIFF profile. Value 2 for inches is preferred., Mandatory for TIFF 6.0 classes B, G, P, R, and Y.1, Mandatory for TIFF/EP., For Exif, mandatory in primary TIFF IFD.
    PageNumber_297 = 297,  // 0x0129  The page number of the page from which this image was scanned.	Extended	Also used by HD Photo
    TransferFunction_301 = 301,  // 0x012D  Describes a transfer function for the image in tabular style.	Extended	 
    Software_305 = 305,  // 0x0131  Name and version number of the software package(s) used to create the image.	Baseline	Listed in LoC Baseline Tags. Document states "Acceptable to include only capture software; preferred to list both capture and post-capture processing software (if applicable), separated by ";".", Req'd in LC NDNP TIFF profile. Include version., Also used by HD Photo., Mandatory for TIFF/EP.
    DateTime_306 = 306,  // 0x0132  Date and time of image creation.	Baseline	Listed in LoC Baseline Tags., Req'd in LC RFP97-6 Section C.4.7. Datetime when scanned., Req'd in LC NDNP TIFF profile., Also used by HD Photo., Usage rule in JHOVE TIFF module., Mandatory for TIFF/EP.
    Artist_315 = 315,  // 0x013B  Person who created the image.	Baseline	Listed in LoC Baseline Tags. Document states "Insitution name followed (if applicable) by ";" and name of scanning contractor., Req'd in LC RFP97-6 Section C.4.7. "Library of Congress."", Req'd in LC NDNP TIFF profile. Provide "institution name; scanning contractor.", Also used by HD Photo
    HostComputer_316 = 316,  // 0x013C  The computer and/or operating system in use at the time of image creation.	Baseline	Also used by HD Photo
    Predictor_317 = 317,  // 0x013D  A mathematical operator that is applied to the image data before an encoding scheme is applied.	Extended	 
    WhitePoint_318 = 318,  // 0x013E  The chromaticity of the white point of the image.	Extended	 
    PrimaryChromaticities_319 = 319,  // 0x013F  The chromaticities of the primaries of the image.	Extended	 
    ColorMap_320 = 320,  // 0x0140  A color map for palette color images.	Baseline	Mandatory for TIFF 6.0 class P.1
    HalftoneHints_321 = 321,  // 0x0141  Conveys to the halftone function the range of gray levels within a colorimetrically-specified image that should retain tonal detail.	Extended	 
    TileWidth_322 = 322,  // 0x0142  The tile width in pixels. This is the number of columns in each tile.	Extended	Mandatory for TIFF 6.0 files that use tiles. (Files that use strips employ tags 273, 278, and 279.), Mandatory in TIFF/EP for tiled images.
    TileLength_323 = 323,  // 0x0143  The tile length (height) in pixels. This is the number of rows in each tile.	Extended	Referenced in JHOVE TIFF module for files that use tiles. (Files that use strips employ tags 273, 278, and 279.), Mandatory in TIFF/EP for tiled images.
    TileOffsets_324 = 324,  // 0x0144  For each tile, the byte offset of that tile, as compressed and stored on disk.	Extended	Mandatory for TIFF 6.0 files that use tiles. (Files that use strips employ tags 273, 278, and 279.), Mandatory in TIFF/EP for tiled images.
    TileByteCounts_325 = 325,  // 0x0145  For each tile, the number of (compressed) bytes in that tile.	Extended	Mandatory for TIFF 6.0 files that use tiles. (Files that use strips employ tags 273, 278, and 279.), Mandatory in TIFF/EP for tiled images.
    BadFaxLines_326 = 326,  // 0x0146  Used in the TIFF-F standard, denotes the number of 'bad' scan lines encountered by the facsimile device.	Extended	 
    CleanFaxData_327 = 327,  // 0x0147  Used in the TIFF-F standard, indicates if 'bad' lines encountered during reception are stored in the data, or if 'bad' lines have been replaced by the receiver.	Extended	 
    ConsecutiveBadFaxLines_328 = 328,  // 0x0148  Used in the TIFF-F standard, denotes the maximum number of consecutive 'bad' scanlines received.	Extended	 
    SubIFDs_330 = 330,  // 0x014A  Offset to child IFDs.	Extended	 
    InkSet_332 = 332,  // 0x014C  The set of inks used in a separated (PhotometricInterpretation=5) image.	Extended	 
    InkNames_333 = 333,  // 0x014D  The name of each ink used in a separated image.	Extended	 
    NumberOfInks_334 = 334,  // 0x014E  The number of inks.	Extended	 
    DotRange_336 = 336,  // 0x0150  The component values that correspond to a 0% dot and 100% dot.	Extended	Usage rule in JHOVE TIFF module.
    TargetPrinter_337 = 337,  // 0x0151  A description of the printing environment for which this separation is intended.	Extended	 
    ExtraSamples_338 = 338,  // 0x0152  Description of extra components.	Baseline	 
    SampleFormat_339 = 339,  // 0x0153  Specifies how to interpret each data sample in a pixel.	Extended	 
    SMinSampleValue_340 = 340,  // 0x0154  Specifies the minimum sample value.	Extended	 
    SMaxSampleValue_341 = 341,  // 0x0155  Specifies the maximum sample value.	Extended	 
    TransferRange_342 = 342,  // 0x0156  Expands the range of the TransferFunction.	Extended	 
    ClipPath_343 = 343,  // 0x0157  Mirrors the essentials of PostScript's path creation functionality.	Extended	Usage rule in JHOVE TIFF module.
    XClipPathUnits_344 = 344,  // 0x0158  The number of units that span the width of the image, in terms of integer ClipPath coordinates.	Extended	Usage rule in JHOVE TIFF module.
    YClipPathUnits_345 = 345,  // 0x0159  The number of units that span the height of the image, in terms of integer ClipPath coordinates.	Extended	 
    Indexed_346 = 346,  // 0x015A  Aims to broaden the support for indexed images to include support for any color space.	Extended	 
    JPEGTables_347 = 347,  // 0x015B  JPEG quantization and/or Huffman tables.	Extended	 
    OPIProxy_351 = 351,  // 0x015F  OPI-related.	Extended	 
    GlobalParametersIFD_400 = 400,  // 0x0190  Used in the TIFF-FX standard to point to an IFD containing tags that are globally applicable to the complete TIFF file.	Extended	 
    ProfileType_401 = 401,  // 0x0191  Used in the TIFF-FX standard, denotes the type of data stored in this file or IFD.	Extended	 
    FaxProfile_402 = 402,  // 0x0192  Used in the TIFF-FX standard, denotes the 'profile' that applies to this file.	Extended	 
    CodingMethods_403 = 403,  // 0x0193  Used in the TIFF-FX standard, indicates which coding methods are used in the file.	Extended	 
    VersionYear_404 = 404,  // 0x0194  Used in the TIFF-FX standard, denotes the year of the standard specified by the FaxProfile field.	Extended	 
    ModeNumber_405 = 405,  // 0x0195  Used in the TIFF-FX standard, denotes the mode of the standard specified by the FaxProfile field.	Extended	 
    Decode_433 = 433,  // 0x01B1  Used in the TIFF-F and TIFF-FX standards, holds information about the ITULAB (PhotometricInterpretation = 10) encoding.	Extended	 
    DefaultImageColor_434 = 434,  // 0x01B2  Defined in the Mixed Raster Content part of RFC 2301, is the default color needed in areas where no image is available.	Extended	 
    JPEGProc_512 = 512,  // 0x0200  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    JPEGInterchangeFormat_513 = 513,  // 0x0201  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    JPEGInterchangeFormatLength_514 = 514,  // 0x0202  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    JPEGRestartInterval_515 = 515,  // 0x0203  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    JPEGLosslessPredictors_517 = 517,  // 0x0205  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    JPEGPointTransforms_518 = 518,  // 0x0206  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    JPEGQTables_519 = 519,  // 0x0207  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    JPEGDCTables_520 = 520,  // 0x0208  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    JPEGACTables_521 = 521,  // 0x0209  Old-style JPEG compression field. TechNote2 invalidates this part of the specification.	Extended	 
    YCbCrCoefficients_529 = 529,  // 0x0211  The transformation from RGB to YCbCr image data.	Extended	Mandatory for TIFF/EP YCbCr images.
    YCbCrSubSampling_530 = 530,  // 0x0212  Specifies the subsampling factors used for the chrominance components of a YCbCr image.	Extended	Mandatory for TIFF/EP YCbCr images.
    YCbCrPositioning_531 = 531,  // 0x0213  Specifies the positioning of subsampled chrominance components relative to luminance samples.	Extended	Mandatory for TIFF/EP YCbCr images.
    ReferenceBlackWhite_532 = 532,  // 0x0214  Specifies a pair of headroom and footroom image data values (codes) for each pixel component.	Extended	Mandatory for TIFF 6.0 class Y.1, Mandatory for TIFF/EP YCbCr images.
    StripRowCounts_559 = 559,  // 0x022F  Defined in the Mixed Raster Content part of RFC 2301, used to replace RowsPerStrip for IFDs with variable-sized strips.	Extended	 
    XMP_700 = 700,  // 0x02BC  XML packet containing XMP metadata	Extended	Also used by HD Photo
    Image_Rating_18246 = 18246, // 0x4746  Ratings tag used by Windows	Exif private IFD	 
    Image_RatingPercent_18249 = 18249, // 0x4749  Ratings tag used by Windows, value as percent	Exif private IFD	 
    ImageID_32781 = 32781, // 0x800D  OPI-related.	Extended	 
    Wang_Annotation_32932 = 32932, // 0x80A4  Annotation data, as used in 'Imaging for Windows'.	Private	 
    CFARepeatPatternDim_33421 = 33421, // 0x828D  For camera raw files from sensors with CFA overlay., TIFF/EP spec, p. 23, Exif private IFD, Mandatory in TIFF/EP for CFA files.
    CFAPattern_33422 = 33422, // 0x828E  For camera raw files from sensors with CFA overlay., TIFF/EP spec, p. 23, Exif private IFD, Mandatory in TIFF/EP for CFA files.
    BatteryLevel_33423 = 33423, // 0x828F  Encodes camera battery level at time of image capture., TIFF/EP spec, p. 45, Exif private IFD
    Copyright_33432 = 33432, // 0x8298  Copyright notice.	Baseline	Also used by HD Photo., Mandatory for TIFF/EP
    ExposureTime_33434 = 33434, // 0x829A  Exposure time, given in seconds.	Exif Private IFD, TIFF/EP spec, p. 38	 
    FNumber_33437 = 33437, // 0x829D  The F number.	Exif Private IFD, TIFF/EP spec, p. 39	 
    MD_FileTag_33445 = 33445, // 0x82A5  Specifies the pixel data format encoding in the Molecular Dynamics GEL file format.	Private	 
    MD_ScalePixel_33446 = 33446, // 0x82A6  Specifies a scale factor in the Molecular Dynamics GEL file format.	Private	 
    MD_ColorTable_33447 = 33447, // 0x82A7  Used to specify the conversion from 16bit to 8bit in the Molecular Dynamics GEL file format.	Private	 
    MD_LabName_33448 = 33448, // 0x82A8  Name of the lab that scanned this file, as used in the Molecular Dynamics GEL file format.	Private	 
    MD_SampleInfo_33449 = 33449, // 0x82A9  Information about the sample, as used in the Molecular Dynamics GEL file format.	Private	 
    MD_PrepDate_33450 = 33450, // 0x82AA  Date the sample was prepared, as used in the Molecular Dynamics GEL file format.	Private	 
    MD_PrepTime_33451 = 33451, // 0x82AB  Time the sample was prepared, as used in the Molecular Dynamics GEL file format.	Private	 
    MD_FileUnits_33452 = 33452, // 0x82AC  Units for data in this file, as used in the Molecular Dynamics GEL file format.	Private	 
    ModelPixelScaleTag_33550 = 33550, // 0x830E  Used in interchangeable GeoTIFF_1_0 files.	Private	 
    IPTC_NAA_33723 = 33723, // 0x83BB  IPTC-NAA (International Press Telecommunications Council-Newspaper Association of America) metadata.	TIFF/EP spec, p. 33	Tag name and values defined by IPTC-NAA Info Interchange Model & Digital Newsphoto Parameter Record., Called IPTS at AWare Web site.
    INGR_Packet_Data_33918 = 33918, // 0x847E  Tag	Intergraph Application specific storage.	Private	 
    INGR_Flag_Registers_33919 = 33919, // 0x847F  Intergraph Application specific flags.	Private	 
    IrasB_Transformation_Matrix_33920 = 33920, // 0x8480  Originally part of Intergraph's GeoTIFF tags, but likely understood by IrasB only.	Private	 
    ModelTiepointTag_33922 = 33922, // 0x8482  Originally part of Intergraph's GeoTIFF tags, but now used in interchangeable GeoTIFF_1_0 files.	Private	In GeoTIFF_1_0, either this tag or 34264 must be defined, but not both
    Site_34016 = 34016,  //  Site where image created.	TIFF/IT spec, 7.2.3	 
    ColorSequence_34017 = 34017,  //  Sequence of colors if other than CMYK.	TIFF/IT spec, 7.2.8.3.2	For BP and BL only2
    IT8Header_34018 = 34018,  //  Certain inherited headers.	TIFF/IT spec, 7.2.3	Obsolete
    RasterPadding_34019 = 34019,  //  Type of raster padding used, if any.	TIFF/IT spec, 7.2.6	 
    BitsPerRunLength_34020 = 34020,  //  Number of bits for short run length encoding.	TIFF/IT spec, 7.2.6	For LW only2
    BitsPerExtendedRunLength_34021 = 34021,  //  Number of bits for long run length encoding.	TIFF/IT spec, 7.2.6	For LW only2
    ColorTable_34022 = 34022,  //  Color value in a color pallette.	TIFF/IT spec, 7.2.8.4	For BP and BL only2
    ImageColorIndicator_34023 = 34023,  //  Indicates if image (foreground) color or transparency is specified.	TIFF/IT spec, 7.2.9	For MP, BP, and BL only2
    BackgroundColorIndicator_34024 = 34024,  //  Background color specification.	TIFF/IT spec, 7.2.9	For BP and BL only2
    ImageColorValue_34025 = 34025,  //  Specifies image (foreground) color.	TIFF/IT spec, 7.2.8.4	For MP, BP, and BL only2
    BackgroundColorValue_34026 = 34026,  //  Specifies background color.	TIFF/IT spec, 7.2.8.4	For BP and BL only2
    PixelIntensityRange_34027 = 34027,  //  Specifies data values for 0 percent and 100 percent pixel intensity.	TIFF/IT spec, 7.2.8.4	For MP only2
    TransparencyIndicator_34028 = 34028,  //  Specifies if transparency is used in HC file.	TIFF/IT spec, 7.2.8.4	For HC only2
    ColorCharacterization_34029 = 34029,  //  Specifies ASCII table or other reference per ISO 12641 and ISO 12642.	TIFF/IT spec, 7.2.8.4	 
    HCUsage_34030 = 34030,  //  Indicates the type of information in an HC file.	TIFF/IT spec, 7.2.6	For HC only2
    TrapIndicator_34031 = 34031,  //  Indicates whether or not trapping has been applied to the file.	TIFF/IT spec, 7.2.6	 
    CMYKEquivalent_34032 = 34032,  //  Specifies CMYK equivalent for specific separations.	TIFF/IT spec, 7.2.8.3.4	 
    Reserved_34033 = 34033,  //  For future TIFF/IT use	TIFF/IT spec	 
    Reserved_34034 = 34034,  //  For future TIFF/IT use	TIFF/IT spec	 
    Reserved_34035 = 34035,  //  For future TIFF/IT use	TIFF/IT spec	 
    ModelTransformationTag_34264 = 34264,  //  0x85D8  Used in interchangeable GeoTIFF_1_0 files.	Private	In GeoTIFF_1_0, either this tag or 33922 must be defined, but not both
    Photoshop_34377 = 34377,  //  0x8649  Collection of Photoshop 'Image Resource Blocks'.	Private	 
    Exif_34665 = 34665,  //  0x8769  IFD	A pointer to the Exif IFD.	Private	Also used by HD Photo., For Exif, mandatory in primary TIFF IFD, if present.
    InterColorProfile_34675 = 34675,  //  0x8773  ICC profile data., TIFF/EP spec, p. 47, Exif private IFD, Also called ICC Profile., Also used by HD Photo
    ImageLayer_34732 = 34732,  //  0x87AC  Defined in the Mixed Raster Content part of RFC 2301, used to denote the particular function of this Image in the mixed raster scheme.	Extended	 
    GeoKeyDirectoryTag_34735 = 34735,  //  0x87AF  Used in interchangeable GeoTIFF_1_0 files.	Private	Mandatory in GeoTIFF_1_0
    GeoDoubleParamsTag_34736 = 34736,  //  0x87B0  Used in interchangeable GeoTIFF_1_0 files.	Private	 
    GeoAsciiParamsTag_34737 = 34737,  //  0x87B1  Used in interchangeable GeoTIFF_1_0 files.	Private	 
    ExposureProgram_34850 = 34850,  //  0x8822  The class of the program used by the camera to set exposure when the picture is taken.	Exif Private IFD, TIFF/EP spec, p. 41	 
    SpectralSensitivity_34852 = 34852,  //  0x8824  Indicates the spectral sensitivity of each channel of the camera used.	Exif Private IFD, TIFF/EP spec, p. 48	 
    GPSInfo_34853 = 34853,  //  0x8825  A pointer to the Exif-related GPS Info IFD., TIFF/EP spec, p. 34, Exif private IFD, Also called GPS IFD.
    ISOSpeedRatings_34855 = 34855,  //  0x8827  Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.	Exif Private IFD, TIFF/EP spec, p. 47	 
    OECF_34856 = 34856,  //  0x8828  Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524.	Exif Private IFD, TIFF/EP spec, p. 48	 
    Interlace_34857 = 34857,  //  0x8829  Indicates the field number of multifield images., TIFF/EP spec, p. 22, Exif private IFD
    TimeZoneOffset_34858 = 34858,  //  0x882A  Encodes time zone of camera clock relative to GMT., TIFF/EP spec, p. 38, Exif private IFD
    SelfTimeMode_34859 = 34859,  //  0x882B  Number of seconds image capture was delayed from button press., TIFF/EP spec, p. 45, Exif private IFD
    SensitivityType_34864 = 34864,  //  0x8830  The SensitivityType tag indicates PhotographicSensitivity tag, which one of the parameters of ISO 12232. Although it is an optional tag, it should be recorded when a PhotographicSensitivity tag is recorded. Value = 4, 5, 6, or 7 may be used in case that the values of plural parameters are the same.	Exif private IFD	 
    StandardOutputSensitivity_34865 = 34865,  //  0x8831  This tag indicates the standard output sensitivity value of a camera or input device defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded.	Exif private IFD	 
    RecommendedExposureIndex_34866 = 34866,  //  0x8832  This tag indicates the recommended exposure index value of a camera or input device defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded.	Exif private IFD	 
    ISOSpeed_34867 = 34867,  //  0x8833  This tag indicates the ISO speed value of a camera or input device that is defined in ISO 12232. When recording this tag, the PhotographicSensitivity and SensitivityType tags shall also be recorded.	Exif private IFD	 
    ISOSpeedLatitudeyyy_34868 = 34868,  //  0x8834  This tag indicates the ISO speed latitude yyy value of a camera or input device that is defined in ISO 12232. However, this tag shall not be recorded without ISOSpeed and ISOSpeedLatitudezzz.	Exif private IFD	 
    ISOSpeedLatitudezzz_34869 = 34869,  //  0x8835  This tag indicates the ISO speed latitude zzz value of a camera or input device that is defined in ISO 12232. However, this tag shall not be recorded without ISOSpeed and ISOSpeedLatitudeyyy.	Exif private IFD	 
    HylaFAX_34908 = 34908,  //  0x885C  FaxRecvParams	Used by HylaFAX.	Private	 
    HylaFAX_34909 = 34909,  //  0x885D  FaxSubAddress	Used by HylaFAX.	Private	 
    HylaFAX_34910 = 34910,  //  0x885E  FaxRecvTime	Used by HylaFAX.	Private	 
    ExifVersion_36864 = 36864,  //  0x9000  The version of the supported Exif standard.	Exif Private IFD	Mandatory in the Exif IFD.
    DateTimeOriginal_36867 = 36867,  //  0x9003  The date and time when the original image data was generated.	Exif Private IFD, TIFF/EP spec, p. 37	Mandatory for TIFF/EP.
    DateTimeDigitized_36868 = 36868,  //  0x9004  The date and time when the image was stored as digital data.	Exif Private IFD	 
    ComponentsConfiguration_37121 = 37121,  //  0x9101  Specific to compressed data; specifies the channels and complements PhotometricInterpretation	Exif Private IFD	 
    CompressedBitsPerPixel_37122 = 37122,  //  0x9102  Specific to compressed data; states the compressed bits per pixel.	Exif Private IFD, TIFF/EP spec, p. 27	 
    ShutterSpeedValue_37377 = 37377,  //  0x9201  Shutter speed.	Exif Private IFD, TIFF/EP spec, p. 39	 
    ApertureValue_37378 = 37378,  //  0x9202  The lens aperture.	Exif Private IFD, TIFF/EP spec, p. 39	 
    BrightnessValue_37379 = 37379,  //  0x9203  The value of brightness.	Exif Private IFD, TIFF/EP spec, p. 40	 
    ExposureBiasValue_37380 = 37380,  //  0x9204  The exposure bias.	Exif Private IFD, TIFF/EP spec, p. 40	 
    MaxApertureValue_37381 = 37381,  //  0x9205  The smallest F number of the lens.	Exif Private IFD, TIFF/EP spec, p. 40	 
    SubjectDistance_37382 = 37382,  //  0x9206  The distance to the subject, given in meters.	Exif Private IFD, TIFF/EP spec, p. 44	 
    MeteringMode_37383 = 37383,  //  0x9207  The metering mode.	Exif Private IFD, TIFF/EP spec, p. 41	 
    LightSource_37384 = 37384,  //  0x9208  The kind of light source.	Exif Private IFD, TIFF/EP spec, p. 46	 
    Flash_37385 = 37385,  //  0x9209  Indicates the status of flash when the image was shot.	Exif Private IFD, TIFF/EP spec, p. 42	 
    FocalLength_37386 = 37386,  //  0x920A  The actual focal length of the lens, in mm.	Exif Private IFD, TIFF/EP spec, p. 44	 
    FlashEnergy_37387 = 37387,  //  0x920B  Amount of flash energy (BCPS).	, TIFF/EP spec, p. 43, Exif Private IFD 
    SpatialFrequencyResponse_37388 = 37388,  //  0x920C  SFR of the camera.	TIFF/EP spec, p. 49, Exif Private IFD
    Noise_37389 = 37389,  //  0x920D  Noise measurement values., TIFF/EP spec, p. 49, Exif Private IFD
    FocalPlaneXResolution_37390 = 37390,  //  0x920E  Number of pixels per FocalPlaneResolutionUnit (37392) in ImageWidth direction for main image., TIFF/EP spec, p. 18, Exif Private IFD
    FocalPlaneYResolution_37391 = 37391,  //  0x920F  Number of pixels per FocalPlaneResolutionUnit (37392) in ImageLength direction for main image.	TIFF/EP spec, p. 19, Exif Private IFD
    FocalPlaneResolutionUnit_37392 = 37392,  //  0x9210  Unit of measurement for FocalPlaneXResolution(37390) and FocalPlaneYResolution(37391).	TIFF/EP spec, p. 19, Exif Private IFD
    ImageNumber_37393 = 37393,  //  0x9211  Number assigned to an image, e.g., in a chained image burst.	TIFF/EP spec, p. 32, Exif Private IFD
    SecurityClassification_37394 = 37394,  //  0x9212  Security classification assigned to the image.	TIFF/EP spec, p. 33, Exif Private IFD37395	9213	ImageHistory	Record of what has been done to the image.	TIFF/EP spec, p. 33, Exif Private IFD
    SubjectLocation_37396 = 37396,  //  0x9214  Indicates the location and area of the main subject in the overall scene.	Exif Private IFD, TIFF/EP spec, p. 45	Called SubjectArea (from Exif spec) at AWare Web site
    ExposureIndex_37397 = 37397,  //  0x9215  Encodes the camera exposure index setting when image was captured.	, TIFF/EP spec, p. 47, Exif Private IFD
    TIFF_EPStandardID_37398 = 37398,  //  0x9216  For current spec, tag value equals 1 0 0 0.	, TIFF/EP spec, p. 16, Exif Private IFD, Mandatory in TIFF/EP.
    SensingMethod_37399 = 37399,  //  0x9217  Type of image sensor.	, TIFF/EP spec, p. 22, Exif Private IFD, Mandatory in TIFF/EP.
    MakerNote_37500 = 37500,  //  0x927C  Manufacturer specific information.	Exif Private IFD	 
    UserComment_37510 = 37510,  //  0x9286  Keywords or comments on the image; complements ImageDescription.	Exif Private IFD	 
    SubsecTime_37520 = 37520,  //  0x9290  A tag used to record fractions of seconds for the DateTime tag.	Exif Private IFD	 
    SubsecTimeOriginal_37521 = 37521,  //  0x9291  A tag used to record fractions of seconds for the DateTimeOriginal tag.	Exif Private IFD	 
    SubsecTimeDigitized_37522 = 37522,  //  0x9292  A tag used to record fractions of seconds for the DateTimeDigitized tag.	Exif Private IFD	 
    ImageSourceData_37724 = 37724,  //  0x935C  Used by Adobe Photoshop.	Private	 
    XPTitle_40091 = 40091,  //  0x9c9b  Title tag used by Windows, encoded in UCS2	Exif Private IFD	 
    XPComment_40092 = 40092,  //  0x9c9c  Comment tag used by Windows, encoded in UCS2	Exif Private IFD	 
    XPAuthor_40093 = 40093,  //  0x9c9d  Author tag used by Windows, encoded in UCS2	Exif Private IFD	 
    XPKeywords_40094 = 40094,  //  0x9c9e  Keywords tag used by Windows, encoded in UCS2	Exif Private IFD	 
    XPSubject_40095 = 40095,  //  0x9c9f  Subject tag used by Windows, encoded in UCS2	Exif Private IFD	 
    FlashpixVersion_40960 = 40960,  //  0xA000  The Flashpix format version supported by a FPXR file.	Exif Private IFD	Mandatory in the Exif IFD
    ColorSpace_40961 = 40961,  //  0xA001  The color space information tag is always recorded as the color space specifier.	Exif Private IFD	Mandatory in the Exif IFD
    PixelXDimension_40962 = 40962,  //  0xA002  Specific to compressed data; the valid width of the meaningful image.	Exif Private IFD	 
    PixelYDimension_40963 = 40963,  //  0xA003  Specific to compressed data; the valid height of the meaningful image.	Exif Private IFD	 
    RelatedSoundFile_40964 = 40964,  //  0xA004  Used to record the name of an audio file related to the image data.	Exif Private IFD	 
    Interoperability_40965 = 40965,  //  0xA005  IFD	A pointer to the Exif-related Interoperability IFD.	Private	 
    FlashEnergy_41483 = 41483,  //  0xA20B  Indicates the strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds	Exif Private IFD	 
    SpatialFrequencyResponse_41484 = 41484,  //  0xA20C  Records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233.	Exif Private IFD	 
    FocalPlaneXResolution_41486 = 41486,  //  0xA20E  Indicates the number of pixels in the image width (X) direction per FocalPlaneResolutionUnit on the camera focal plane.	Exif Private IFD	 
    FocalPlaneYResolution_41487 = 41487,  //  0xA20F  Indicates the number of pixels in the image height (Y) direction per FocalPlaneResolutionUnit on the camera focal plane.	Exif Private IFD	 
    FocalPlaneResolutionUnit_41488 = 41488,  //  0xA210  Indicates the unit for measuring FocalPlaneXResolution and FocalPlaneYResolution.	Exif Private IFD	 
    SubjectLocation_41492 = 41492,  //  0xA214  Indicates the location of the main subject in the scene.	Exif Private IFD	 
    ExposureIndex_41493 = 41493,  //  0xA215  Indicates the exposure index selected on the camera or input device at the time the image is captured.	Exif Private IFD	 
    SensingMethod_41495 = 41495,  //  0xA217  Indicates the image sensor type on the camera or input device.	Exif Private IFD	 
    FileSource_41728 = 41728,  //  0xA300  Indicates the image source.	Exif Private IFD	Req'd in LC NDNP TIFF profile. Values: "microfilm," "microfiche," or "print."
    SceneType_41729 = 41729,  //  0xA301  Indicates the type of scene.	Exif Private IFD	 
    CFAPattern_41730 = 41730,  //  0xA302  Indicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used.	Exif Private IFD	 
    CustomRendered_41985 = 41985,  //  0xA401  Indicates the use of special processing on image data, such as rendering geared to output.	Exif Private IFD	 
    ExposureMode_41986 = 41986,  //  0xA402  Indicates the exposure mode set when the image was shot.	Exif Private IFD	 
    WhiteBalance_41987 = 41987,  //  0xA403  Indicates the white balance mode set when the image was shot.	Exif Private IFD	 
    DigitalZoomRatio_41988 = 41988,  //  0xA404  Indicates the digital zoom ratio when the image was shot.	Exif Private IFD	 
    FocalLengthIn35mmFilm_41989 = 41989,  //  0xA405  Indicates the equivalent focal length assuming a 35mm film camera, in mm.	Exif Private IFD	 
    SceneCaptureType_41990 = 41990,  //  0xA406  Indicates the type of scene that was shot.	Exif Private IFD	 
    GainControl_41991 = 41991,  //  0xA407  Indicates the degree of overall image gain adjustment.	Exif Private IFD	 
    Contrast_41992 = 41992,  //  0xA408  Indicates the direction of contrast processing applied by the camera when the image was shot.	Exif Private IFD	 
    Saturation_41993 = 41993,  //  0xA409  Indicates the direction of saturation processing applied by the camera when the image was shot.	Exif Private IFD	 
    Sharpness_41994 = 41994,  //  0xA40A  Indicates the direction of sharpness processing applied by the camera when the image was shot.	Exif Private IFD	 
    DeviceSettingDescription_41995 = 41995,  //  0xA40B  This tag indicates information on the picture-taking conditions of a particular camera model.	Exif Private IFD	 
    SubjectDistanceRange_41996 = 41996,  //  0xA40C  Indicates the distance to the subject.	Exif Private IFD	 
    ImageUniqueID_42016 = 42016,  //  0xA420  Indicates an identifier assigned uniquely to each image.	Exif Private IFD	Req'd in LC NDNP TIFF profile. Microfilm reel sequence number. If from paper: "issue date-edition-page sequence."
    CameraOwnerName_42032 = 42032,  //  0xa430  Camera owner name as ASCII string.	Exif Private IFD	 
    BodySerialNumber_42033 = 42033,  //  0xa431  Camera body serial number as ASCII string.	Exif Private IFD	 
    LensSpecification_42034 = 42034,  //  0xa432  This tag notes minimum focal length, maximum focal length, minimum F number in the minimum focal length, and minimum F number in the maximum focal length, which are specification information for the lens that was used in photography. When the minimum F number is unknown, the notation is 0/0.	Exif Private IFD	 
    LensMake_42035 = 42035,  //  0xa433  Lens manufacturer name as ASCII string.	Exif Private IFD	 
    LensModel_42036 = 42036,  //  0xa434  Lens model name and number as ASCII string.	Exif Private IFD	 
    LensSerialNumber_42037 = 42037,  //  0xa434  Lens serial number as ASCII string.	Exif Private IFD	 
    GDAL_METADATA_42112 = 42112,  //  0xA480  Used by the GDAL library, holds an XML list of name=value 'metadata' values about the image as a whole, and about specific samples.	Private	 
    GDAL_NODATA_42113 = 42113,  //  0xA481  Used by the GDAL library, contains an ASCII encoded nodata or background pixel value.	Private	 
    PixelFormat_48129 = 48129,  //  0xBC01  A 128-bit Globally Unique Identifier (GUID) that identifies the image pixel format.	HD Photo Feature Spec, p. 17	 
    Transformation_48130 = 48130,  //  0xBC02  Specifies the transformation to be applied when decoding the image to present the desired representation.	HD Photo Feature Spec, p. 23	 
    Uncompressed_48131 = 48131,  //  0xBC03  Specifies that image data is uncompressed.	HD Photo Feature Spec, p. 23	 
    ImageType_48132 = 48132,  //  0xBC04  Specifies the image type of each individual frame in a multi-frame file.	HD Photo Feature Spec, p. 27	 
    ImageWidth_48256 = 48256,  //  0xBC80  Specifies the number of columns in the transformed photo, or the number of pixels per scan line.	HD Photo Feature Spec, p. 21	 
    ImageHeight_48257 = 48257,  //  0xBC81  Specifies the number of pixels or scan lines in the transformed photo.	HD Photo Feature Spec, p. 21	 
    WidthResolution_48258 = 48258,  //  0xBC82  Specifies the horizontal resolution of a transformed image expressed in pixels per inch.	HD Photo Feature Spec, p. 21	 
    HeightResolution_48259 = 48259,  //  0xBC83  Specifies the vertical resolution of a transformed image expressed in pixels per inch.	HD Photo Feature Spec, p. 21	 
    ImageOffset_48320 = 48320,  //  0xBCC0  Specifies the byte offset pointer to the beginning of the photo data, relative to the beginning of the file.	HD Photo Feature Spec, p. 22	 
    ImageByteCount_48321 = 48321,  //  0xBCC1  Specifies the size of the photo in bytes.	HD Photo Feature Spec, p. 22	 
    AlphaOffset_48322 = 48322,  //  0xBCC2  Specifies the byte offset pointer the beginning of the planar alpha channel data, relative to the beginning of the file.	HD Photo Feature Spec, p. 22	 
    AlphaByteCount_48323 = 48323,  //  0xBCC3  Specifies the size of the alpha channel data in bytes.	HD Photo Feature Spec, p. 23	 
    ImageDataDiscard_48324 = 48324,  //  0xBCC4  Signifies the level of data that has been discarded from the image as a result of a compressed domain transcode to reduce the file size.	HD Photo Feature Spec, p. 25	 
    AlphaDataDiscard_48325 = 48325,  //  0xBCC5  Signifies the level of data that has been discarded from the planar alpha channel as a result of a compressed domain transcode to reduce the file size.	HD Photo Feature Spec, p. 26	 
    OceScanjobDescription_50215 = 50215,  //  0xC427  Used in the Oce scanning process.	Private	 
    OceApplicationSelector_50216 = 50216,  //  0xC428  Used in the Oce scanning process.	Private	 
    OceIdentificationNumber_50217 = 50217,  //  0xC429  Used in the Oce scanning process.	Private	 
    OceImageLogicCharacteristics_50218 = 50218,  //  0xC42A  Used in the Oce scanning process.	Private	 
    PrintImageMatching_50341 = 50341,  //  0xC4A5  Description needed.	Exif Private IFD	 
    DNGVersion_50706 = 50706,  //  0xC612  Encodes DNG four-tier version number; for version 1.1.0.0, the tag contains the bytes 1, 1, 0, 0. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 17, Exif Private IFD
    DNGBackwardVersion_50707 = 50707,  //  0xC613  Defines oldest version of spec with which file is compatible. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 17, Exif Private IFD
    UniqueCameraModel_50708 = 50708,  //  0xC614  Unique, non-localized nbame for camera model. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 18, Exif Private IFD
    LocalizedCameraModel_50709 = 50709,  //  0xC615  Similar to 50708, with localized camera name. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 19, Exif Private IFD
    CFAPlaneColor_50710 = 50710,  //  0xC616  Mapping between values in the CFAPattern tag and the plane numbers in LinearRaw space. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 19, Exif Private IFD, quired for non-RGB CFA images.
    CFALayout_50711 = 50711,  //  0xC617  Spatial layout of the CFA. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 20, Exif Private IFD
    LinearizationTable_50712 = 50712,  //  0xC618  Lookup table that maps stored values to linear values. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 21, Exif Private IFD
    BlackLevelRepeatDim_50713 = 50713,  //  0xC619  Repeat pattern size for BlackLevel tag. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 21, Exif Private IFD
    BlackLevel_50714 = 50714,  //  0xC61A  Specifies the zero light encoding level.Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 22, Exif Private IFD
    BlackLevelDeltaH_50715 = 50715,  //  0xC61B  Specifies the difference between zero light encoding level for each column and the baseline zero light encoding level. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 22, Exif Private IFD
    BlackLevelDeltaV_50716 = 50716,  //  0xC61C  Specifies the difference between zero light encoding level for each row and the baseline zero light encoding level. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 23, Exif Private IFD
    WhiteLevel_50717 = 50717,  //  0xC61D  Specifies the fully saturated encoding level for the raw sample values. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 24, Exif Private IFD
    DefaultScale_50718 = 50718,  //  0xC61E  For cameras with non-square pixels, specifies the default scale factors for each direction to convert the image to square pixels. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 24, Exif Private IFD
    DefaultCropOrigin_50719 = 50719,  //  0xC61F  Specifies the origin of the final image area, ignoring the extra pixels at edges used to prevent interpolation artifacts. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 25, Exif Private IFD
    DefaultCropSize_50720 = 50720,  //  0xC620  Specifies size of final image area in raw image coordinates. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 26, Exif Private IFD
    ColorMatrix_50721 = 50721,  //  0xC621  Defines a transformation matrix that converts XYZ values to reference camera native color space values, under the first calibration illuminant. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 27, Exif Private IFD
    ColorMatrix_50722 = 50722,  //  0xC622  Defines a transformation matrix that converts XYZ values to reference camera native color space values, under the second calibration illuminant. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 28, Exif Private IFD
    CameraCalibration_50723 = 50723,  //  0xC623  Defines a calibration matrix that transforms reference camera native space values to individual camera native space values under the first calibration illuminant. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 28, Exif Private IFD
    CameraCalibration_50724 = 50724,  //  0xC624  Defines a calibration matrix that transforms reference camera native space values to individual camera native space values under the second calibration illuminant. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 29, Exif Private IFD
    ReductionMatrix_50725 = 50725,  //  0xC625  Defines a dimensionality reduction matrix for use as the first stage in converting color camera native space values to XYZ values, under the first calibration illuminant. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 30, Exif Private IFD
    ReductionMatrix_50726 = 50726,  //  0xC626  Defines a dimensionality reduction matrix for use as the first stage in converting color camera native space values to XYZ values, under the second calibration illuminant. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 30, Exif Private IFD
    AnalogBalance_50727 = 50727,  //  0xC627  Pertaining to white balance, defines the gain, either analog or digital, that has been applied to the stored raw values. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 31, Exif Private IFD
    AsShotNeutral_50728 = 50728,  //  0xC628  Specifies the selected white balance at the time of capture, encoded as the coordinates of a perfectly neutral color in linear reference space values. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 31, Exif Private IFD
    AsShotWhiteXY_50729 = 50729,  //  0xC629  Specifies the selected white balance at the time of capture, encoded as x-y chromaticity coordinates. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 32, Exif Private IFD
    BaselineExposure_50730 = 50730,  //  0xC62A  Specifies in EV units how much to move the zero point for exposure compensation. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 32, Exif Private IFD
    BaselineNoise_50731 = 50731,  //  0xC62B  Specifies the relative noise of the camera model at a baseline ISO value of 100, compared to reference camera model. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 33, Exif Private IFD
    BaselineSharpness_50732 = 50732,  //  0xC62C  Specifies the relative amount of sharpening required for this camera model, compared to reference camera model. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 33, Exif Private IFD
    BayerGreenSplit_50733 = 50733,  //  0xC62D  For CFA images, specifies, in arbitrary units, how closely the values of the green pixels in the blue/green rows track the values of the green pixels in the red/green rows. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 34, Exif Private IFD
    LinearResponseLimit_50734 = 50734,  //  0xC62E  Specifies the fraction of the encoding range above which the response may become significantly non-linear. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 34, Exif Private IFD
    CameraSerialNumber_50735 = 50735,  //  0xC62F  Serial number of camera. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 35, Exif Private IFD
    LensInfo_50736 = 50736,  //  0xC630  Information about the lens. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 35, Exif Private IFD
    ChromaBlurRadius_50737 = 50737,  //  0xC631  Normally for non-CFA images, provides a hint about how much chroma blur ought to be applied. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 36, Exif Private IFD
    AntiAliasStrength_50738 = 50738,  //  0xC632  Provides a hint about the strength of the camera's anti-aliasing filter. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 36, Exif Private IFD
    ShadowScale_50739 = 50739, //  Used by Adobe Camera Raw to control sensitivity of its shadows slider. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 37, Exif Private IFD
    DNGPrivateData_50740 = 50740,  //  0xC634  Provides a way for camera manufacturers to store private data in DNG files for use by their own raw convertors. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 37, Exif Private IFD
    MakerNoteSafety_50741 = 50741,  //  0xC635  Lets the DNG reader know whether the Exif MakerNote tag is safe to preserve. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 38, Exif Private IFD
    CalibrationIlluminant_50778 = 50778,  //  0xC65A  Illuminant used for first set of calibration tags. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 26, Exif Private IFD
    CalibrationIlluminant_50779 = 50779,  //  0xC65B  Illuminant used for second set of calibration tags. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 27, Exif Private IFD
    BestQualityScale_50780 = 50780,  //  0xC65C  Specifies the amount by which the values of the DefaultScale tag need to be multiplied to achieve best quality image size. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 25, Exif Private IFD
    RawDataUniqueID_50781 = 50781, //  Contains a 16-byte unique identifier for the raw image file in the DNG file. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 39, Exif Private IFD
    AliasLayerMetadata_50784 = 50784,  //  0xC660  Alias Sketchbook Pro layer usage description.	Private	 
    OriginalRawFileName_50827 = 50827, //  Name of original file if the DNG file results from conversion from a non-DNG raw file. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 39, Exif Private IFD
    OriginalRawFileData_50828 = 50828, //  If the DNG file was converted from a non-DNG raw file, then this tag contains the original raw data. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 40, Exif Private IFD
    ActiveArea_50829 = 50829, //  Defines the active (non-masked) pixels of the sensor. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 41, Exif Private IFD
    MaskedAreas_50830 = 50830, //  List of non-overlapping rectangle coordinates of fully masked pixels, which can optimally be used by DNG readers to measure the black encoding level. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 42, Exif Private IFD
    AsShotICCProfile_50831 = 50831, //  Contains ICC profile that, in conjunction with the AsShotPreProfileMatrix tag, specifies a default color rendering from camera color space coordinates (linear reference values) into the ICC profile connection space. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 42, Exif Private IFD
    AsShotPreProfileMatrix_50832 = 50832, //  Specifies a matrix that should be applied to the camera color space coordinates before processing the values through the ICC profile specified in the AsShotICCProfile tag. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 43, Exif Private IFD
    CurrentICCProfile_50833 = 50833, //  The CurrentICCProfile and CurrentPreProfileMatrix tags have the same purpose and usage as the AsShotICCProfile and AsShotPreProfileMatrix tag pair, except they are for use by raw file editors rather than camera manufacturers. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 44, Exif Private IFD
    CurrentPreProfileMatrix_50834 = 50834, //  The CurrentICCProfile and CurrentPreProfileMatrix tags have the same purpose and usage as the AsShotICCProfile and AsShotPreProfileMatrix tag pair, except they are for use by raw file editors rather than camera manufacturers. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 44, Exif Private IFD
    ColorimetricReference_50879 = 50879,  //  0xC6BF  The DNG color model documents a transform between camera colors and CIE XYZ values. This tag describes the colorimetric reference for the CIE XYZ values. 0 = The XYZ values are scene-referred. 1 = The XYZ values are output-referred, using the ICC profile perceptual dynamic range. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 45, Exif Private IFD
    CameraCalibrationSignature_50931 = 50931,  //  0xC6F3  A UTF-8 encoded string associated with the CameraCalibration1 and CameraCalibration2 tags. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 46, Exif Private IFD
    ProfileCalibrationSignature_50932 = 50932,  //  0xC6F4  A UTF-8 encoded string associated with the camera profile tags. Used in IFD 0 or CameraProfile IFD of DNG files.	DNG spec (1.3, 2009), p. 46, Exif Private IFD
    ExtraCameraProfiles_50933 = 50933,  //  0xC6F5  A list of file offsets to extra Camera Profile IFDs. The format of a camera profile begins with a 16-bit byte order mark (MM or II) followed by a 16-bit "magic" number equal to 0x4352 (CR), a 32-bit IFD offset, and then a standard TIFF format IFD. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 47
    AsShotProfileName_50934 = 50934,  //  0xC6F6  A UTF-8 encoded string containing the name of the "as shot" camera profile, if any. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 47,Exif Private IFD
    NoiseReductionApplied_50935 = 50935,  //  0xC6F7  Indicates how much noise reduction has been applied to the raw data on a scale of 0.0 to 1.0. A 0.0 value indicates that no noise reduction has been applied. A 1.0 value indicates that the "ideal" amount of noise reduction has been applied, i.e. that the DNG reader should not apply additional noise reduction by default. A value of 0/0 indicates that this parameter is unknown. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 48,Exif Private IFD
    ProfileName_50936 = 50936,  //  0xC6F8  A UTF-8 encoded string containing the name of the camera profile. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 48,Exif Private IFD
    ProfileHueSatMapDims_50937 = 50937,  //  0xC6F9  Specifies the number of input samples in each dimension of the hue/saturation/value mapping tables. The data for these tables are stored in ProfileHueSatMapData1 and ProfileHueSatMapData2 tags. Allowed values include the following: HueDivisions >= 1; SaturationDivisions >= 2; ValueDivisions >=1. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 49,Exif Private IFD
    ProfileHueSatMapData_50938 = 50938,  //  0xC6FA  Contains the data for the first hue/saturation/value mapping table. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees; the second entry is saturation scale factor; and the third entry is a value scale factor. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 50,Exif Private IFD
    ProfileHueSatMapData_50939 = 50939,  //  0xC6FB  Contains the data for the second hue/saturation/value mapping table. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees; the second entry is saturation scale factor; and the third entry is a value scale factor. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 50-1,Exif Private IFD
    ProfileToneCurve_50940 = 50940,  //  0xC6FC  Contains a default tone curve that can be applied while processing the image as a starting point for user adjustments. , e curve is specified as a list of 32-bit IEEE floating-point value pairs in linear gamma. Each sample has an input value in the range of 0.0 to 1.0, and an output value in the range of 0.0 to 1.0. The first sample is required to be (0.0, 0.0), and the last sample is required to be (1.0, 1.0). Interpolated the curve using a cubic spline. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 51,Exif Private IFD
    ProfileEmbedPolicy_50941 = 50941,  //  0xC6FD  Contains information about the usage rules for the associated camera profile. The valid values and meanings are: 0 = “allcopying”; 1 = “embed if used”; 2 = “embed never”; and 3 = “no restrictions”. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 52,Exif Private IFD
    ProfileCopyright_50942 = 50942,  //  0xC6FE  Contains information about the usage rules for the associated camera profile. The valid values and meanings are: 0 = “allow copying”; 1 = “embed if used”; 2 = “embed never”; and 3 = “no restrictions”. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 52,Exif Private IFD
    ForwardMatrix_50964 = 50964,  //  0xC714  Defines a matrix that maps white balanced camera colors to XYZ D50 colors. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 53,Exif Private IFD
    ForwardMatrix_50965 = 50965,  //  0xC715  Defines a matrix that maps white balanced camera colors to XYZ D50 colors. Used in IFD 0 or Camera Profile IFD of DNG files.	DNG spec (1.3, 2009), p. 54, Exif Private IFD
    PreviewApplicationName_50966 = 50966,  //  0xC716  A UTF-8 encoded string containing the name of the application that created the preview stored in the IFD. Used in Preview IFD of DNG files.	DNG spec (1.3, 2009), p. 54, Exif Private IFD
    PreviewApplicationVersion_50967 = 50967,  //  0xC717  A UTF-8 encoded string containing the version number of the application that created the preview stored in the IFD. Used in Preview IFD of DNG files.	DNG spec (1.3, 2009), p. 55, Exif Private IFD
    PreviewSettingsName_50968 = 50968,  //  0xC718  A UTF-8 encoded string containing the name of the conversion settings (for example, snapshot name) used for the preview stored in the IFD. Used in Preview IFD of DNG files.	DNG spec (1.3, 2009), p. 55, Exif Private IFD
    PreviewSettingsDigest_50969 = 50969,  //  0xC719  A unique ID of the conversion settings (for example, MD5 digest) used to render the preview stored in the IFD. Used in Preview IFD of DNG files.	DNG spec (1.3, 2009), p. 56, Exif Private IFD
    PreviewColorSpace_50970 = 50970,  //  0xC71A  This tag specifies the color space in which the rendered preview in this IFD is stored. The valid values include: 0 = Unknown; 1 = Gray Gamma 2.2; 2 = sRGB; 3 = Adobe RGB; and 4 = ProPhoto RGB. Used in Preview IFD of DNG files.	DNG spec (1.3, 2009), p. 56, Exif Private IFD
    PreviewDateTime_50971 = 50971,  //  0xC71B  This tag is an ASCII string containing the name of the date/time at which the preview stored in the IFD was rendered, encoded using ISO 8601 format. Used in Preview IFD of DNG files.	DNG spec (1.3, 2009), p. 57, Exif Private IFD
    RawImageDigest_50972 = 50972,  //  0xC71C  MD5 digest of the raw image data. All pixels in the image are processed in row-scan order. Each pixel is zero padded to 16 or 32 bits deep (16-bit for data less than or equal to 16 bits deep, 32-bit otherwise). The data is processed in little-endian byte order. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 57, Exif Private IFD
    OriginalRawFileDigest_50973 = 50973,  //  0xC71D  MD5 digest of the data stored in the OriginalRawFileData tag. Used in IFD 0 of DNG files.	DNG spec (1.3, 2009), p. 58, Exif Private IFD
    SubTileBlockSize_50974 = 50974,  //  0xC71E  Normally, pixels within a tile are stored in simple row-scan order. This tag specifies that the pixels within a tile should be grouped first into rectangular blocks of the specified size. These blocks are stored in row-scan order. Within each block, the pixels are stored in row-scan order. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 58, Exif Private IFD
    RowInterleaveFactor_50975 = 50975,  //  0xC71F  Specifies that rows of the image are stored in interleaved order. The value of the tag specifies the number of interleaved fields. Used in Raw IFD of DNG files.	DNG spec (1.3, 2009), p. 59, Exif Private IFD
    ProfileLookTableDims_50981 = 50981,  //  0xC725  Specifies the number of input samples in each dimension of a default "look" table. The data for this table is stored in the ProfileLookTableData tag. Allowed values include: HueDivisions >= 1; SaturationDivisions >= 2; and ValueDivisions >= 1. Used in IFD 0 or Camera Profile IFD of DNG files.	 DNG spec (1.3, 2009), p. 59, Exif Private IFD
    ProfileLookTableData_50982 = 50982,  //  0xC726  Default "look" table that can be applied while processing the image as a starting point for user adjustment. This table uses the same format as the tables stored in the ProfileHueSatMapData1 and ProfileHueSatMapData2 tags, and is applied in the same color space. However, it should be applied later in the processing pipe, after any exposure compensation and/or fill light stages, but before any tone curve stage. Each entry of the table contains three 32-bit IEEE floating-point values. The first entry is hue shift in degrees, the second entry is a saturation scale factor, and the third entry is a value scale factor. Used in IFD 0 or Camera Profile IFD of DNG files.	 DNG spec (1.3, 2009), p. 60, Exif Private IFD
    OpcodeList_51008 = 51008,  //  0xC740  Specifies the list of opcodes (image processing operation codes) that should be applied to the raw image, as read directly from the file. Used in Raw IFD of DNG files.	 DNG spec (1.3, 2009), p. 61, Exif Private IFD
    OpcodeList_51009 = 51009,  //  0xC741  Specifies the list of opcodes (image processing operation codes) that should be applied to the raw image, just after it has been mapped to linear reference values. Used in Raw IFD of DNG files.	 DNG spec (1.3, 2009), p. 61, Exif Private IFD
    OpcodeList_51022 = 51022,  //  0xC74E  Specifies the list of opcodes (image processing operation codes) that should be applied to the raw image, just after it has been demosaiced. Used in Raw IFD of DNG files.	 DNG spec (1.3, 2009), p. 62, Exif Private IFD
    NoiseProfile_51041 = 51041,  //  0xC761  Describes the amount of noise in a raw image; models the amount of signal-dependent photon (shot) noise and signal-independent sensor readout noise, two common sources of noise in raw images. Used in Raw IFD of DNG files.	 DNG spec (1.3, 2009), p. 62-3, Exif Private IFD
    OriginalDefaultFinalSize_51089 = 51089,  //  0xC791  If this file is a proxy for a larger original DNG file, this tag specifics the default final size of the larger original file from which this proxy was generated. The default value for this tag is default final size of the current DNG file, which is DefaultCropSize * DefaultScale.	DNG spec (1.4, 2012), p. 74	 
    OriginalBestQualityFinalSize_51090 = 51090,  //  0xC792  If this file is a proxy for a larger original DNG file, this tag specifics the best quality final size of the larger original file from which this proxy was generated. The default value for this tag is the OriginalDefaultFinalSize, if specified. Otherwise the default value for this tag is the best quality size of the current DNG file, which is DefaultCropSize * DefaultScale * BestQualityScale.	DNG spec (1.4, 2012), p. 75	 
    OriginalDefaultCropSize_51091 = 51091,  //  0xC793  If this file is a proxy for a larger original DNG file, this tag specifics the DefaultCropSize of the larger original file from which this proxy was generated. The default value for this tag is the OriginalDefaultFinalSize, if specified. Otherwise, the default value for this tag is the DefaultCropSize of the current DNG file.	DNG spec (1.4, 2012), p. 75	 
    ProfileHueSatMapEncoding_51107 = 51107,  //  0xC7A3  Provides a way for color profiles to specify how indexing into a 3D HueSatMap is performed during raw conversion. This tag is not applicable to 2.5D HueSatMap tables (i.e., where the Value dimension is 1). The currently defined values are: 0 = Linear encoding (method described in DNG spec); 1 = sRGB encoding (method described in DNG spec).	DNG spec (1.4, 2012), p. 73	 
    ProfileLookTableEncoding_51108 = 51108,  //  0xC7A4  Provides a way for color profiles to specify how indexing into a 3D LookTable is performed during raw conversion. This tag is not applicable to a 2.5D LookTable (i.e., where the Value dimension is 1). The currently defined values are: 0 = Linear encoding (method described in DNG spec); 1 = sRGB encoding (method described in DNG spec).	DNG spec (1.4, 2012), p. 72-3	 
    BaselineExposureOffset_51109 = 51109,  //  0xC7A5  Provides a way for color profiles to increase or decrease exposure during raw conversion. BaselineExposureOffset specifies the amount (in EV units) to add to th e BaselineExposure tag during image rendering. For example, if the BaselineExposure value fo r a given camera model is +0.3, and the BaselineExposureOffset value for a given camera profile used to render an image for that camera model is -0.7, then th e actual default exposure value used during rendering will be +0.3 - 0.7 = -0.4.	DNG spec (1.4, 2012), p. 71	 
    DefaultBlackRender_51110 = 51110,  //  0xC7A6  This optional tag in a color profile provides a hint to the raw converter regarding how to handle the black point (e.g., flare subtraction) during rendering. The currently defined values are: 0 = Auto; 1 = None. If set to Auto, the raw converter should perform black subtraction during rendering. The amount and method of black subtraction may be automatically determined and may be image-dependent. If set to None, the raw converter should not perform any black subtraction during rendering. This may be desirable when using color lookup tables (e.g., LookTable) or tone curves in camera profiles to perform a fixed, consistent level of black subtraction.	DNG spec (1.4, 2012), p. 71	 
    NewRawImageDigest_51111 = 51111,  //  0xC7A7  This tag is a modified MD5 digest of the raw image data. It has been updated from the algorithm used to compute the RawImageDigest tag be more multi-processor friendly, and to support lossy compression algorithms. The details of the algorithm used to compute this tag are documented in the Adobe DNG SDK source code.	DNG spec (1.4, 2012), p. 76	 
    RawToPreviewGain_51112 = 51112,  //  0xC7A8  The gain (what number the sample values are multiplied by) between the main raw IFD and the preview IFD containing this tag.	DNG spec (1.4, 2012), p. 76	 
    DefaultUserCrop_51125 = 51125,  //  0xC7B5  Specifies a default user crop rectangle in relative coordinates. The values must satisfy: 0.0 <= top < bottom <= 1.0; 0.0 <= left < right <= 1.0. The default values of (top = 0, left = 0, bottom = 1, right = 1) correspond exactly to the default crop rectangle (as specified by the DefaultCropOrigin and DefaultCropSize tags).	DNG spec (1.4, 2012), p. 70	 
}